# Generated by Django 3.1 on 2021-05-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_Users',
            fields=[
                ('mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
