# Generated by Django 3.1 on 2021-06-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_users',
            name='mobile',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
