# Generated by Django 3.1 on 2021-06-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_auto_20210603_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_users',
            name='counter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
